### PR TITLE
Add osx builds.

### PR DESCRIPTION
**Pull request by erykoff**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
@conda-forge/libxkbfile This is ready for review.  Thanks!

**Comment by hmaarrfk** [comment]
were you still interested in this?

**Comment by hmaarrfk** [comment]
This recipe might need a little help from an other maintainer. do you want to add yourself?

**Comment by erykoff** [comment]
I am still interested in this (though it wasn't urgent), and I've added myself to the maintainer list.  Thanks!

**Pull request merged**
